services:
  redl-db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
  mongo:
    image: mongo:7.0
    volumes:
      - mondata:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PG_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PG_PASS}
  reverse-proxy:
    image: nginx:1.31
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:latest
    command: redis-server --requirepass ${PG_PASS}
  mongoView:
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${PG_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PG_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${PG_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${PG_PASS}


volumes:
  pgdata: 
  mondata: