// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chatOps.api.Models;

#nullable disable

namespace chatOps.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720020218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("joinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("roomId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("roomId");

                    b.HasIndex("userId");

                    b.ToTable("RoomUser");
                });

            modelBuilder.Entity("chatOps.api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("about")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("links")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("roomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("roomId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("chatOps.api.Room", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("roomId"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("tags")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("roomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.HasOne("chatOps.api.Room", "Room")
                        .WithMany("UsersRooms")
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("chatOps.api.Models.User", "User")
                        .WithMany("UsersRooms")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chatOps.api.Models.User", b =>
                {
                    b.HasOne("chatOps.api.Room", null)
                        .WithMany("blacklisted")
                        .HasForeignKey("roomId");
                });

            modelBuilder.Entity("chatOps.api.Models.User", b =>
                {
                    b.Navigation("UsersRooms");
                });

            modelBuilder.Entity("chatOps.api.Room", b =>
                {
                    b.Navigation("UsersRooms");

                    b.Navigation("blacklisted");
                });
#pragma warning restore 612, 618
        }
    }
}
