// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using chatOps.api.Models;

#nullable disable

namespace chatOps.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomTag", b =>
                {
                    b.Property<int>("RoomsroomId")
                        .HasColumnType("integer")
                        .HasColumnName("roomsroom_id");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer")
                        .HasColumnName("tags_id");

                    b.HasKey("RoomsroomId", "TagsId")
                        .HasName("pk_room_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_room_tag_tags_id");

                    b.ToTable("room_tag", (string)null);
                });

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("joinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("roomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_room_user");

                    b.HasIndex("roomId")
                        .HasDatabaseName("ix_room_user_room_id");

                    b.HasIndex("userId")
                        .HasDatabaseName("ix_room_user_user_id");

                    b.ToTable("room_user", (string)null);
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("colour");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("chatOps.api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("background_image");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("integer")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecondaryEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_email");

                    b.Property<string>("about")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.PrimitiveCollection<string[]>("links")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("links");

                    b.Property<int?>("roomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("roomId")
                        .HasDatabaseName("ix_users_room_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("chatOps.api.Room", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("roomId"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTime>("created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("roomId")
                        .HasName("pk_rooms");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("RoomTag", b =>
                {
                    b.HasOne("chatOps.api.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_tag_rooms_roomsroom_id");

                    b.HasOne("Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_tag_tags_tags_id");
                });

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.HasOne("chatOps.api.Room", "Room")
                        .WithMany("UsersRooms")
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_user_rooms_room_id");

                    b.HasOne("chatOps.api.Models.User", "User")
                        .WithMany("UsersRooms")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_user_users_user_id");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("chatOps.api.Models.User", b =>
                {
                    b.HasOne("chatOps.api.Room", null)
                        .WithMany("blacklisted")
                        .HasForeignKey("roomId")
                        .HasConstraintName("fk_users_rooms_room_id");
                });

            modelBuilder.Entity("chatOps.api.Models.User", b =>
                {
                    b.Navigation("UsersRooms");
                });

            modelBuilder.Entity("chatOps.api.Room", b =>
                {
                    b.Navigation("UsersRooms");

                    b.Navigation("blacklisted");
                });
#pragma warning restore 612, 618
        }
    }
}
